Traceback (most recent call last):
  File "/media/ubuntu/Newdisk/xyo/admin/aacc_80/wwwroot/eachcity.py", line 329, in <module>
    a=eachcityscore(sys.argv[1],sys.argv[2],sys.argv[3])
  File "/media/ubuntu/Newdisk/xyo/admin/aacc_80/wwwroot/eachcity.py", line 249, in eachcityscore
    dicsosan['서산'][day[p]]=blist[2][p]
IndexError: index 365 is out of bounds for axis 0 with size 365
